---
title: "Buzzmetrics"
author: "Team Buzzmetrics"
date: "24 September 2014"
output: html_document
---

Some preliminaries...

```{r}
require(data.table)
require(ggplot2)

dataPath <- '../data'
```

Helper to read a CSV file in the data path keyed by DOI:

```{r}
readDataFileWithDOI <- function(fileName) {
  table <- data.table(read.csv(file.path(dataPath, fileName), header=TRUE))
  setkey(table, 'doi')
  table
}
```

Load data from the various feature files:

```{r}
dataStem <- file.path('altmetric','1d-2014-09-24')
outFilePath <- function(fileName) { file.path('out', dataStem, fileName) }

titles <- readDataFileWithDOI(paste0(dataStem, '.csv'))

questionMarks <- readDataFileWithDOI(outFilePath('question_marks.csv'))
questionMarks$question_marks <- factor(questionMarks$question_marks)

colons <- readDataFileWithDOI(outFilePath('colons.csv'))
colons$colons <- factor(colons$colons)

titleLengths <- readDataFileWithDOI(outFilePath('title_lengths.csv'))
titleLengths <- data.table(doi = titleLengths$doi,
                           title_length = titleLengths$length)
```

Go from publication date to an age in weeks, which is a bit easier to interpret:

```{r}
titles$pub_date <- as.POSIXct(titles$pub_date)
titles$age_weeks <- as.numeric(difftime(as.POSIXct('2014-09-25', tz='UTC'),
                                        titles$pub_date,
                                        units="weeks"))
```

Merge everything together on DOI:

```{r}
data <- titles
data <- data[questionMarks]
data <- data[colons]
data <- data[titleLengths]
```

Summary table:

```{r}
print(summary(data))
```

Some simple plots:

```{r, echo=FALSE}
ggplot(data) + geom_point(aes(x=age_weeks, y=log(score), color=question_marks))
```

```{r, echo=FALSE}
ggplot(data) + geom_point(aes(x=age_weeks, y=log(score), color=title_length))
```

The simplest regression that could possibly work:

```{r}
bigLm <- lm(score ~ age_weeks + question_marks + colons + title_length,
            data=data)
print(summary(bigLm))
```
