require "bundler/gem_tasks"

#
# See notes in data/out/README.md about naming conventions
#
# Examples:
#
# mkdir -p ../../data/out/altmetric/sample
# rake run[../../data/altmetric/sample.csv,../../data/out/altmetric/sample]
#
# mkdir -p ../../data/out/altmetric/1d-2014-09-24
# rake run[../../data/altmetric/1d-2014-09-24.csv,../../data/out/altmetric/1d-2014-09-24]
#
# mkdir -p ../../data/out/altmetric/1m-partial-2014-09-24
# rake run[../../data/altmetric/1m-partial-2014-09-24.csv,../../data/out/altmetric/1m-partial-2014-09-24]
#
task :run, [:origin, :destin] do |t, args|
  require 'buzzmetrics'
  include Buzzmetrics

  fail "need origin arg" unless args[:origin]
  fail "need destin arg" unless args[:destin]

  fail "destin arg must be a directory" unless Dir.exists?(args[:destin])

  input_csv = File.read(args[:origin])

  question_mark input_csv, File.join(args[:destin], 'question_marks.csv')
  colons input_csv, File.join(args[:destin], 'colons.csv')
  word_prevalence input_csv, File.join(args[:destin], 'word_prevalence.csv')

  ["title_lengths_csv", "average_word_length", "median_word_length"].each do |metric|
    Buzzmetrics.send(metric, input_csv, File.join(args[:destin], metric + ".csv"))
  end
end
